### ISSUE TITLE
Naming of segments vs the table they belong to

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/bulk-memory-operations#122]
Perhaps I'm missing some context but its seems like previouly valid wat files are no longer valid under this proposal because the meaning on the `$name` in the top level elem segments changed:

```
(elem $foo (i32.const 0))
```

Currently `$foo` names a table, but with this proposal `$foo` now names the element segment itself.

This change be seen in the changes to `test/core/elem.wast` compared to upstream.

This (AFAICT) s causing some problems in in wabt today: https://github.com/WebAssembly/wabt/pull/1193.

**Comment by rossberg** [comment]
Yes, I think you're right. Technically, this is indeed a breaking change to the text format (the same applies to data segments, FWIW). However, it seems fairly minor in practice, since the name was pretty much useless before, so was hardly used, and moreover, the only valid modules that actually break are ones that have *multiple* element segments with explicit named table references.

Is it worth backporting this change to the MVP to avoid the wabt hack?

**Comment by sbc100** [comment]
I ended up ignoring elem names unless bulk memory is enabled: https://github.com/WebAssembly/wabt/pull/1193.

It seems to work OK for now.   If this seems like a reasonable approach we can close this issue.
