### ISSUE TITLE
table.copy overwriting behaviour

### ISSUE THREAD

**Issue by julian-seward1** [WebAssembly/bulk-memory-operations#25]
Is it allowed to use table.copy to copy undefined entries on top of defined entries?  To be more precise, I think that actually falls into four related questions:

(1) is it allowable for table.copy to read undefined entries (from the source area) ?
(2) if (1), is it allowable for table.copy to write undefined entries (to the destination area) ?
(3) if (2), is it allowable for table.copy to write an undefined entry on top of a defined one?
(4) if (3), should the overwriting of a defined entry by an undefined one be regarded as first applying 'table.drop' to the overwritten entry?

**Comment by rossberg** [comment]
I'd say the answer is clearly yes to (1)-(3), since an "undefined" entry is merely a null reference in the larger scheme of things, and we will allow arbitrary reference values in tables in the future anyway.

I don't understand your item (4). Table.drop does not apply to table entries but to (passive) element segments defined in a module.

**Comment by julian-seward1** [comment]
> I don't understand your item (4).
Ah yes, you're right of course, my mistake.  Muddy thinking on my part.
