### ISSUE TITLE
Memory mapping?

### ISSUE THREAD

**Issue by JakeSmarter** [WebAssembly/bulk-memory-operations#52]
What about memory mapping, like `memory.map`, to host physical or virtual address spaces? This should enable direct interaction with all kinds of devices. Another use case may be access to non-swappable memory to protect sensitive data.

Yes, this would enable to place data and code outside the VM but would also enable new concepts. Modules using a `memory.map` instruction could/should be signed and thus trusted for execution.

**Comment by GITNE** [comment]
> I think memory.map fits better as a host-imported function, since it depends on the host environment's notions of files/devices, etc.

In that sense every instruction depends on the host implementation. Maybe I was not clear enough. Communication with devices via mapped memory could be just one use case. A more common use case might be efficient IPC. Yes, you can implement all kinds of host specific features via module imports and other VM extensions but implementing IPC via memory mapping and a dedicated bytecode is actually crucial for code portability and reusability, especially on non-browser implementations, since Wasm does not and should not specify module APIs.

I am not saying that a memory mapping feature should or must be part of the bulk memory operations proposal but it is worth to think about adding this functionality to the VM.
