### ISSUE TITLE
Change passive element segment encoding

### ISSUE THREAD

**Issue by binji** [WebAssembly/bulk-memory-operations#98]
We discussed this at the 2019 June CG meeting, and decided to update the passive element segment encoding.

See https://github.com/WebAssembly/meetings/blob/master/2019/CG-06.md#bulk-memory--hr (particularly the slides).

**Comment by binji** [comment]
Proposed encoding (from slide 14):

| Flags Value | Segment Type | Externval Index / Element Expression | Table 0 / Table index field |
| - | - | - | - |
| 0 | Active | Externval index | Table 0 |
| 1 | Active | Element expression | Table 0 |
| 2 | Active | Externval index | Table index field |
| 3 | Active | Element expression | Table index field |
| 4 | Passive | Externval index | N/A |
| 5 | Passive | Element expression | N/A |
| 6 | Declared | Externval index | N/A |

Memory layout (from slide 16)

| Name | flags | - | - | - | - | - |
| - | - | - | - | - | - | - |
| Active, externval, table 0 | 0 | offset | func 0 | func 1 | func 2 | func 3 |
| Active, elemexpr, table 0 | 1 | offset | ref.func | func 0 | end | |
| Active, externval, table index | 2 | offset | table index | externkind | index 0 | index 1 |
| Active, elemexpr, table index | 3 | offset | table index | ref.func | func 0 | end |
| Passive, externval | 4 | elemtype | externkind | index 0 | index 1 | index 2 |
| Passive, elemexpr | 5 | elemtype | ref.func | func 0 | end | |
| Declared, externval | 6 | externkind | index 0 | index 1 | index 2 | index 3 |

Any concerns with this?

**Comment by lars-t-hansen** [comment]
No concerns.

**Comment by titzer** [comment]
I guess this is a bikeshedding thread. :-)

What about making the low-order bit of the flags field for the first table indicate whether a table index immediate follows? That way, no table lookup is necessary for a decoder to skip to the next entry, just a bit check.

**Comment by rossberg** [comment]
I generally would prefer compatibility with the flag layout for data segments, i.e., use more bits, but have the same bits mean the same thing. I also wouldn't mind a bit more separation of te various dimensions.

For data segments we have:

| Bit | Meaning |
| - | - |
| 0 | is passive |
| 1 | is zero idx (if bit 0 clear) or clear otherwise |

For elements that would suggest:

| Bit | Meaning |
| - | - |
| 0 | is passive |
| 1 | is zero idx (if bit 0 clear) or is declared (if bit 0 set) |
| 2 | is elemexpr |

That is, we add bit 2, and reuse bit 1 for a previously unused case.

Furthermore, I would suggest to put the table index first if present, directly after the flag. That's consistent with data segments, plus that way the special backwards compat case with table 0 can be viewed as just a compression of two consecutive bytes.

Together that would yield:

| Flag | Meaning | Field | Field | Field | Payload |
| - | - | - | - | - | - |
| 0 | legacy active, externval | | offset | | idx* |
| 1 | passive, externval | | | externkind | idx* |
| 2 | active, externval | tableidx | offset | externkind | idx*|
| 3 | declared, externval | | | externkind | idx* |
| 4 | legacy active, elemexpr | | offset | | expr* |
| 5 | passive, elemexpr | | | elemtype | expr* |
| 6 | active, elemexpr | tableidx | offset | elemtype | expr*|
| 7 | declared, elemexpr | | | elemtype | expr* |

Other than renumbering, the only difference to your scheme is the tableidx put first and that it allows declared segments with elemexpr (which seems easy).

We could also reorder the flags to make this table look nicer, but then we should do the same for data segments.

**Comment by tlively** [comment]
I think having separate meanings for each bit as in @rossberg's scheme is a good idea.

**Comment by binji** [comment]
@tlively there are separate meanings in my proposal too, I've updated to show what they mean, and updated the table to match his format too. That said, I'm ok w/ @rossberg's proposal too.

**Comment by tlively** [comment]
Oh right, thanks for making those explicit. I'd be fine with either of these schemes.

**Comment by rossberg** [comment]
Yes, the main point of my modification  is consistency with data segments and consistency regarding the presence of elemtype.

**Comment by binji** [comment]
OK, let's do @rossberg's scheme then. @lars-t-hansen OK w/ you?

**Comment by lars-t-hansen** [comment]
Sure, no problem.

**Comment by rossberg** [comment]
This was done.
